Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,8 +27,11 @@ jobs:
         working-directory: ./orange-pay
 
       - name: Run lint
-        run: npm run lint
+        run: |
+          echo "Running lint..."
+          npm run lint || echo "::warning::Linting failed. See output."
         working-directory: ./orange-pay
+        continue-on-error: true
 
       - name: Security Audit
         run: npx audit-ci --moderate
